### ISSUE TITLE
Tried reimplementing it on php

### ISSUE THREAD

**Issue by renevall** [mackstann/binpack#1]
What does this line do?

```
    if(this.left != null)
        return this.left.insert_rect(rect) || this.right.insert_rect(rect);
```

**Comment by mackstann** [comment]
The if condition checks whether the node has children. If it does, it tries to insert the rect into the left one, or, failing, that, the right one. If it was able to insert the rect into either, it returns the node where it was inserted (which was returned by one of the two insert_rect recursive calls). If it wasn't able to insert it on either side, it ultimately returns null.
